name: Deploy Prompt

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'staging'
      version:
        description: 'Version to deploy'
        required: true

jobs:
  show-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Echo inputs
        run: |
          echo "Environment: ${{ github.event.inputs.env }}"
          echo "Version: ${{ github.event.inputs.version }}"
