name: Simple Prompt

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter a message'
        required: true
        default: 'Hello from GitHub Actions!'

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo the message
        run: echo "You entered: ${{ github.event.inputs.message }}"
