name: Prompt for Input

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'staging'
      version:
        description: 'Version to deploy'
        required: true
