name: Prompt for Input

on:
  workflow_dispatch:
    inputs:
      user_message:
        description: 'Enter your message or value'
        required: true
        default: 'Hello from GitHub Actions!'

jobs:
  echo-input:
    runs-on: ubuntu-latest

    steps:
      - name: Show input value
        run: echo "You entered: ${{ github.event.inputs.user_message }}"
